image: "sseemayer/rust-musl-builder-mingw:latest"

stages:
  - test
  - build

test:
  stage: test
  script:
  - rustc --version && cargo --version
  - cd compiler
  - cargo test --all --verbose
  - cd ../gbt
  - cargo test --all --verbose

linux-musl:
  stage: build
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/gbc
      - target/x86_64-unknown-linux-musl/release/gbt
  script:
    - cargo build --release --target x86_64-unknown-linux-musl
    - strip -S target/x86_64-unknown-linux-musl/release/gbc
    - cd gbt
    - cargo build --release --target x86_64-unknown-linux-musl
    - cd ..
    - strip -S target/x86_64-unknown-linux-musl/release/gbt

windows-mingw:
  stage: build
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/gbc.exe
      - target/x86_64-pc-windows-gnu/release/gbt.exe
  script:
    - cargo build --release --target x86_64-pc-windows-gnu
    - cd gbt
    - cargo build --release --target x86_64-pc-windows-gnu
