[package]
name = "gbasm"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]
edition = "2018"

[dependencies]
gbasm-lib = { version = "0.1.0", path = "./gbasm-lib"  }
clap = "2.33.0"

