[package]
name = "gbc"
version = "0.5.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]
edition = "2018"

[dependencies]
compiler = { version = "0.5.0", path = "./compiler"  }
clap = "2.33.0"

[profile.release]
lto = true
