[package]
name = "gbc"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]
edition = "2018"

[dependencies]
gbc-lib = { version = "0.1.0", path = "./gbc-lib"  }
clap = "2.33.0"


[profile.release]
lto = true
