[workspace]
resolver = "2"
members = [
    "compiler",
    "decompiler",
    "file-io",
    "gb-cpu",
    "gb-cpu/gb-types",
    "gbt",
    "project",
    "."
]

[package]
name = "gbc"
version = "0.7.3"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]
edition = "2018"

[dependencies]
toml = "0.5.3"
serde = { version = "*", features = ["derive"] }
decompiler = { version = "0.1.0", path = "./decompiler" }
compiler = { version = "0.7.2", path = "./compiler" }
file-io = { version = "0.5.0", path = "./file-io" }
project = { version = "0.5.0", path = "./project" }
clap = "2.33.0"

[profile.dev.package.compiler]
opt-level = 3

[profile.release]
lto = 'fat'
codegen-units = 1

[profile.dev.package.gbd]
overflow-checks = false
opt-level = 3

[profile.dev.package.edt]
overflow-checks = false
opt-level = 3

[profile.dev.package.analyzer]
overflow-checks = false
opt-level = 3

[profile.dev.package.arrayvec]
overflow-checks = false
opt-level = 3

[profile.dev.package.pixels]
overflow-checks = false
opt-level = 3

[profile.dev.package.imgui]
overflow-checks = false
opt-level = 3

[profile.dev.package.winit]
overflow-checks = false
opt-level = 3

[profile.dev.package.wgpu-hal]
overflow-checks = false
opt-level = 3

[profile.dev.package.wgpu]
overflow-checks = false
opt-level = 3

[profile.dev.package.parking_lot]
overflow-checks = false
opt-level = 3

[profile.dev.package.wgpu-core]
overflow-checks = false
opt-level = 3

[profile.dev.package.cpal]
overflow-checks = false
opt-level = 3

[profile.dev.package.sameboy-rs-sys]
overflow-checks = false
opt-level = 3

[profile.dev.package.sameboy-rs]
overflow-checks = false
opt-level = 3

