[package]
name = "decompiler"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]
edition = "2018"

[dependencies]
gb-cpu = { version = "0.5.0", path = "../gb-cpu"  }
file-io = { version = "0.5.0", path = "../file-io"  }
colored = "1.7"

