// External Dependencies ------------------------------------------------------
use clap::{Arg, Command};

pub fn app<'help>() -> Command<'help> {
    Command::new("gbc")
        .version("0.8.0")
        .author("Ivo Wetzel <ivo.wetzel@googlemail.com>")
        .about("GameBoy Compiler")
        .subcommand(
            Command::new("release")
                .about("Builds a release ROM using the local \"gbc.toml\" project configuration.")
        )
        .subcommand(
            Command::new("debug")
                .about("Builds a debug ROM using the local \"gbc.toml\" project configuration.")
        )
        .subcommand(
            Command::new("emu")
                .about("Builds a ROM and emulates it via the specified configuration.")
                .arg(Arg::new("EMULATOR")
                    .help("Emulator config to use")
                    .required(true)
                    .index(1)
                )
        )
        .arg(Arg::new("SOURCE_FILE")
            .help("Input source file")
            .index(1)
        )
        .arg(Arg::new("ROM_FILE")
            .long("output-rom")
            .short('o')
            .value_name("FILE")
            .takes_value(true)
            .help("ROM file to generate")
        )
        .arg(Arg::new("MAP_FILE")
            .long("symbol-map")
            .short('m')
            .value_name("FILE")
            .takes_value(true)
            .help("Output symbol mapping for BGB debugger")
        )
        .arg(Arg::new("info")
            .long("info")
            .short('i')
            .help("Display ROM info")
        )
        .arg(Arg::new("segments")
            .long("segments")
            .short('S')
            .help("Display segments usage")
        )
        .arg(Arg::new("silent")
            .long("silent")
            .short('s')
            .help("Surpress all output")
        )
        .arg(Arg::new("no-optimize")
            .long("no-optimize")
            .help("Disable instruction optimizations")
        )
        .arg(Arg::new("debug")
            .long("debug")
            .short('D')
            .help("Enable debug instructions for BGB debugger")
        )
        .arg(Arg::new("decompile")
            .long("decompile")
            .short('d')
            .help("Decompile the input file instead")
        )
}
