[package]
name = "gbc-lib"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]
edition = "2018"

[dependencies]
gbc-cpu = { version = "0.1.0", path = "gbc-cpu"  }
ordered-float = "1.0.1"
lazy_static = "1.3.0"

[dev-dependencies]
regex = "1"

